# Generated by Django 6.1 on 2026-08-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64, unique=True)),
                (
                    "nivel",
                    models.PositiveSmallIntegerField(
                        help_text="1 para Primera, 2 para Segunda", unique=True
                    ),
                ),
                (
                    "n_descensos",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Equipos que descienden al final de temporada",
                    ),
                ),
            ],
            options={
                "ordering": ["nivel"],
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Jornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                (
                    "cerrada",
                    models.BooleanField(
                        default=False,
                        help_text="Resultados registrados y modelo re-entrenado",
                    ),
                ),
            ],
            options={
                "ordering": ["temporada", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Temporada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=32, unique=True)),
                ("inicio", models.DateField()),
                ("fin", models.DateField()),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-inicio"],
            },
        ),
        migrations.CreateModel(
            name="Jugador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "es_importante",
                    models.BooleanField(
                        default=False, help_text="Jugador clave para su equipo"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugadores",
                        to="ligas.equipo",
                    ),
                ),
            ],
            options={
                "ordering": ["equipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goles_local",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "goles_visitante",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                (
                    "jornada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos",
                        to="ligas.jornada",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_como_local",
                        to="ligas.equipo",
                    ),
                ),
                (
                    "visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_como_visitante",
                        to="ligas.equipo",
                    ),
                ),
            ],
            options={
                "ordering": ["jornada", "fecha", "id"],
                "unique_together": {("jornada", "local", "visitante")},
            },
        ),
        migrations.CreateModel(
            name="Prediccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prob_local", models.FloatField()),
                ("prob_empate", models.FloatField()),
                ("prob_visitante", models.FloatField()),
                (
                    "resultado_predicho",
                    models.CharField(
                        choices=[
                            ("1", "Gana Local"),
                            ("X", "Empate"),
                            ("2", "Gana Visitante"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "resultado_real",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Gana Local"),
                            ("X", "Empate"),
                            ("2", "Gana Visitante"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("acierto", models.BooleanField(blank=True, null=True)),
                ("fecha_prediccion", models.DateTimeField(auto_now_add=True)),
                (
                    "partido",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediccion",
                        to="ligas.partido",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_prediccion"],
            },
        ),
        migrations.AddField(
            model_name="jornada",
            name="temporada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jornadas",
                to="ligas.temporada",
            ),
        ),
        migrations.CreateModel(
            name="Ausencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[("lesion", "Lesión"), ("sancion", "Sanción")],
                        max_length=16,
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ausencias",
                        to="ligas.jugador",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ausencias",
                        to="ligas.partido",
                    ),
                ),
            ],
            options={
                "unique_together": {("partido", "jugador")},
            },
        ),
        migrations.CreateModel(
            name="Participacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posicion_final",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participaciones",
                        to="ligas.division",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participaciones",
                        to="ligas.equipo",
                    ),
                ),
                (
                    "temporada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participaciones",
                        to="ligas.temporada",
                    ),
                ),
            ],
            options={
                "ordering": ["temporada", "division", "posicion_final"],
                "unique_together": {("temporada", "equipo")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="jornada",
            unique_together={("temporada", "numero")},
        ),
    ]
