# Generated by Django 6.1 on 2026-08-20 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="color_primario",
            field=models.CharField(
                blank=True,
                default="#1e293b",
                help_text="Color principal en formato #RRGGBB (acento en la UI).",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="color_secundario",
            field=models.CharField(
                blank=True,
                default="#0f172a",
                help_text="Color secundario en formato #RRGGBB.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="equipo",
            name="escudo",
            field=models.ImageField(
                blank=True,
                help_text="Imagen o icono del escudo del equipo.",
                null=True,
                upload_to="escudos/",
            ),
        ),
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proxima_jornada",
                    models.ForeignKey(
                        blank=True,
                        help_text="Próxima jornada para predecir resultados.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ligas.jornada",
                    ),
                ),
                (
                    "temporada_actual",
                    models.ForeignKey(
                        blank=True,
                        help_text="Temporada que se muestra por defecto en el dashboard.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ligas.temporada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración",
                "verbose_name_plural": "Configuración",
            },
        ),
    ]
