# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligas", "0002_equipo_color_primario_equipo_color_secundario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partido",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
    ]
