# Generated by Django 6.1 on 2026-08-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ligas", "0003_alter_partido_fecha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiniela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        help_text="Número de Quiniela / Jornada de Quiniela"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo de la Quiniela", max_length=64
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Marcar como la Quiniela activa para el simulador",
                    ),
                ),
                (
                    "cerrada",
                    models.BooleanField(
                        default=False, help_text="Resultados evaluados"
                    ),
                ),
                ("n_dobles", models.PositiveSmallIntegerField(default=2)),
                ("n_triples", models.PositiveSmallIntegerField(default=1)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "jornada",
                    models.ForeignKey(
                        blank=True,
                        help_text="Jornada deportiva asociada (opcional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quinielas",
                        to="ligas.jornada",
                    ),
                ),
                (
                    "temporada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quinielas",
                        to="ligas.temporada",
                    ),
                ),
            ],
            options={
                "ordering": ["-temporada__inicio", "-numero"],
                "unique_together": {("temporada", "numero")},
            },
        ),
        migrations.AddField(
            model_name="configuracion",
            name="quiniela_actual",
            field=models.ForeignKey(
                blank=True,
                help_text="Quiniela activa para el simulador.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ligas.quiniela",
            ),
        ),
        migrations.CreateModel(
            name="CasillaQuiniela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posicion",
                    models.PositiveSmallIntegerField(
                        help_text="Posición en el boleto (1 a 15)"
                    ),
                ),
                (
                    "signo_base",
                    models.CharField(
                        choices=[
                            ("1", "Gana Local"),
                            ("X", "Empate"),
                            ("2", "Gana Visitante"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "tipo_apuesta",
                    models.CharField(
                        choices=[
                            ("FIJO", "Fijo"),
                            ("DOBLE", "Doble"),
                            ("TRIPLE", "Triple"),
                        ],
                        default="FIJO",
                        max_length=10,
                    ),
                ),
                (
                    "signos_jugados",
                    models.CharField(
                        default="1",
                        help_text="Signos jugados: '1', '1X', '1X2', etc.",
                        max_length=8,
                    ),
                ),
                (
                    "pronostico_pleno",
                    models.CharField(
                        blank=True,
                        help_text="Para casilla 15: ej. '1-0', 'M-1'",
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "resultado_real",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("acierto", models.BooleanField(blank=True, null=True)),
                (
                    "partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casillas_quiniela",
                        to="ligas.partido",
                    ),
                ),
                (
                    "quiniela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casillas",
                        to="ligas.quiniela",
                    ),
                ),
            ],
            options={
                "ordering": ["quiniela", "posicion"],
                "unique_together": {("quiniela", "partido"), ("quiniela", "posicion")},
            },
        ),
    ]
