# Generated by Django 6.1 on 2026-08-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ligas", "0004_quiniela_configuracion_quiniela_actual_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="casillaquiniela",
            unique_together={("quiniela", "posicion")},
        ),
    ]
