# Generated by Django 6.1

from django.db import migrations, models


def init_divisions(apps, schema_editor):
    Division = apps.get_model("ligas", "Division")
    # Actualizar 1ª División Masc
    div1 = Division.objects.filter(nivel=1).first()
    if div1:
        div1.categoria = "MASC"
        div1.codigo = "1DIV"
        div1.n_champions = 4
        div1.n_descensos = 3
        div1.save(update_fields=["categoria", "codigo", "n_champions", "n_descensos"])

    # Actualizar 2ª División Masc
    div2 = Division.objects.filter(nivel=2).first()
    if div2:
        div2.categoria = "MASC"
        div2.codigo = "2DIV"
        div2.n_champions = 0
        div2.n_descensos = 4
        div2.save(update_fields=["categoria", "codigo", "n_champions", "n_descensos"])

    # Crear Liga F si no existe
    if not Division.objects.filter(categoria="FEM", nivel=1).exists():
        Division.objects.create(
            nombre="1ª División Femenina (Liga F)",
            categoria="FEM",
            nivel=1,
            codigo="LIGA_F",
            n_champions=3,
            n_descensos=2,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("ligas", "0005_alter_casillaquiniela_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={"ordering": ["categoria", "nivel"]},
        ),
        migrations.AddField(
            model_name="division",
            name="categoria",
            field=models.CharField(
                choices=[("MASC", "Fútbol Masculino"), ("FEM", "Fútbol Femenino")],
                default="MASC",
                help_text="Fútbol Masculino o Femenino",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="codigo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Identificador corto ej. '1DIV', '2DIV', 'LIGA_F'",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="n_champions",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Equipos clasificados para Champions League (o UWCL)",
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="nivel",
            field=models.PositiveSmallIntegerField(
                help_text="Nivel jerárquico dentro de su categoría (1 para Primera, 2 para Segunda)"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="division",
            unique_together={("categoria", "nivel")},
        ),
        migrations.RunPython(init_divisions, reverse_code=migrations.RunPython.noop),
    ]
